<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="imu"> 

    <!-- IMU 属性 -->
    <xacro:property name="imu_length"   value="0.02" /> <!-- IMU长度(x) -->
    <xacro:property name="imu_width"    value="0.025" /> <!-- IMU宽度(y) -->
    <xacro:property name="imu_height"   value="0.03" /> <!-- IMU高度(z) -->
    <xacro:property name="imu_x"        value="-0.08" />
    <xacro:property name="imu_y"        value="0.0" />
    <xacro:property name="imu_z"        value="${base_link_length / 2 + imu_height / 2}" />

    <!-- 默认惯性参数 -->
    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </xacro:macro>

    <!-- IMU 传感器宏 -->
    <xacro:macro name="imu" params="prefix:=imu">
        
        <!-- IMU 链接 -->
        <link name="imu_link">
            <visual>
               <origin rpy="0 0 0" xyz="${imu_x} ${imu_y} ${imu_z}" />
               <geometry>
                    <box size="${imu_length} ${imu_width} ${imu_height}"/>
               </geometry>                
              <material name="red"/>
            </visual>
            <collision>
                <box size="${imu_length} ${imu_length} ${imu_height}"/>
            </collision>
        </link>

        <!-- 关节连接 imu_link 和 base_link -->
        <joint name="imu_to_base" type="fixed">
            <parent link="base_link"/>
            <child link="imu_link"/>
            <origin rpy="0 0 0" xyz="${imu_x} ${imu_y} ${imu_z}"/>
        </joint>

        <!-- Gazebo 配置 -->
        <gazebo reference="${prefix}_link">
            <gravity>true</gravity>
            <sensor name="imu_sensor" type="imu">
                <always_on>true</always_on>
                <update_rate>100</update_rate>
                <visualize>true</visualize>
                <topic>__default_topic__</topic>
                <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
                    <topicName>imu</topicName>         
                    <bodyName>imu_link</bodyName>
                    <updateRateHZ>100.0</updateRateHZ>    
                    <gaussianNoise>0.0</gaussianNoise>   
                    <xyzOffset>0 0 0</xyzOffset>     
                    <rpyOffset>0 0 0</rpyOffset>
                    <frameName>imu_link</frameName>        
                </plugin>
                <pose>0 0 0 0 0 0</pose>
            </sensor>
        </gazebo>

    </xacro:macro>

</robot>
