<!-- 组合小车底盘与传感器 -->
<robot name="my_car_camera" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- 属性封装 -->
    <xacro:arg name="gpu" default="true"/>
    <xacro:property name="gpu" value="$(arg gpu)" />
    <xacro:arg name="organize_cloud" default="true"/>
    <xacro:property name="organize_cloud" value="$(arg organize_cloud)" />

    <xacro:include filename="$(find robot_description)/urdf/my_head.xacro" />
    <xacro:include filename="$(find robot_description)/urdf/my_base.xacro" />
    <xacro:include filename="$(find robot_description)/urdf/my_camera.xacro" />
    <xacro:include filename="$(find robot_description)/urdf/move.xacro" />

    <!-- 更新结构信息，以laser_support + velodyne 为构建，不需要自己写雷达仿真的xacro文件 -->
    <!-- <xacro:include filename="my_laser.urdf.xacro" /> -->
    <!-- <xacro:include filename="my_sensors_laser.urdf.xacro" /> -->

    <!-- VLP16 激光雷达 -->
    <xacro:include filename="$(find robot_description)/urdf/laser_support.xacro" />
    <xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>
    <xacro:VLP-16 parent="support" name="velodyne" topic="/velodyne_points" organize_cloud="${organize_cloud}" hz="10" samples="440" gpu="${gpu}">
          <origin xyz="0 0 ${support_length/2}" rpy="0 0 0" />
    </xacro:VLP-16>

    <!-- IMU 模块 -->
    <xacro:include filename="$(find robot_description)/urdf/my_imu.xacro"/>

    <!-- 摄像头模块 -->
    <xacro:include filename="$(find robot_description)/urdf/my_camera.xacro" />

</robot>