// Generated by gencpp from file qr_msgs/qr.msg
// DO NOT EDIT!


#ifndef QR_MSGS_MESSAGE_QR_H
#define QR_MSGS_MESSAGE_QR_H

#include <ros/service_traits.h>


#include <qr_msgs/qrRequest.h>
#include <qr_msgs/qrResponse.h>


namespace qr_msgs
{

struct qr
{

typedef qrRequest Request;
typedef qrResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct qr
} // namespace qr_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qr_msgs::qr > {
  static const char* value()
  {
    return "8035d02e9aa155dc8ea6018792abfea1";
  }

  static const char* value(const ::qr_msgs::qr&) { return value(); }
};

template<>
struct DataType< ::qr_msgs::qr > {
  static const char* value()
  {
    return "qr_msgs/qr";
  }

  static const char* value(const ::qr_msgs::qr&) { return value(); }
};


// service_traits::MD5Sum< ::qr_msgs::qrRequest> should match
// service_traits::MD5Sum< ::qr_msgs::qr >
template<>
struct MD5Sum< ::qr_msgs::qrRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qr_msgs::qr >::value();
  }
  static const char* value(const ::qr_msgs::qrRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qr_msgs::qrRequest> should match
// service_traits::DataType< ::qr_msgs::qr >
template<>
struct DataType< ::qr_msgs::qrRequest>
{
  static const char* value()
  {
    return DataType< ::qr_msgs::qr >::value();
  }
  static const char* value(const ::qr_msgs::qrRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qr_msgs::qrResponse> should match
// service_traits::MD5Sum< ::qr_msgs::qr >
template<>
struct MD5Sum< ::qr_msgs::qrResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qr_msgs::qr >::value();
  }
  static const char* value(const ::qr_msgs::qrResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qr_msgs::qrResponse> should match
// service_traits::DataType< ::qr_msgs::qr >
template<>
struct DataType< ::qr_msgs::qrResponse>
{
  static const char* value()
  {
    return DataType< ::qr_msgs::qr >::value();
  }
  static const char* value(const ::qr_msgs::qrResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QR_MSGS_MESSAGE_QR_H
