// Generated by gencpp from file qr_msgs/qrRequest.msg
// DO NOT EDIT!


#ifndef QR_MSGS_MESSAGE_QRREQUEST_H
#define QR_MSGS_MESSAGE_QRREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qr_msgs
{
template <class ContainerAllocator>
struct qrRequest_
{
  typedef qrRequest_<ContainerAllocator> Type;

  qrRequest_()
    : start_calling(false)  {
    }
  qrRequest_(const ContainerAllocator& _alloc)
    : start_calling(false)  {
  (void)_alloc;
    }



   typedef uint8_t _start_calling_type;
  _start_calling_type start_calling;





  typedef boost::shared_ptr< ::qr_msgs::qrRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qr_msgs::qrRequest_<ContainerAllocator> const> ConstPtr;

}; // struct qrRequest_

typedef ::qr_msgs::qrRequest_<std::allocator<void> > qrRequest;

typedef boost::shared_ptr< ::qr_msgs::qrRequest > qrRequestPtr;
typedef boost::shared_ptr< ::qr_msgs::qrRequest const> qrRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qr_msgs::qrRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qr_msgs::qrRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qr_msgs::qrRequest_<ContainerAllocator1> & lhs, const ::qr_msgs::qrRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start_calling == rhs.start_calling;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qr_msgs::qrRequest_<ContainerAllocator1> & lhs, const ::qr_msgs::qrRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qr_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qr_msgs::qrRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qr_msgs::qrRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qr_msgs::qrRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qr_msgs::qrRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qr_msgs::qrRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qr_msgs::qrRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qr_msgs::qrRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09c1c6dfb3988f60c7afde4296358c38";
  }

  static const char* value(const ::qr_msgs::qrRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09c1c6dfb3988f60ULL;
  static const uint64_t static_value2 = 0xc7afde4296358c38ULL;
};

template<class ContainerAllocator>
struct DataType< ::qr_msgs::qrRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qr_msgs/qrRequest";
  }

  static const char* value(const ::qr_msgs::qrRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qr_msgs::qrRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool start_calling\n"
;
  }

  static const char* value(const ::qr_msgs::qrRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qr_msgs::qrRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_calling);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct qrRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qr_msgs::qrRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qr_msgs::qrRequest_<ContainerAllocator>& v)
  {
    s << indent << "start_calling: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start_calling);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QR_MSGS_MESSAGE_QRREQUEST_H
