local_costmap:
  global_frame: modifier_map
  robot_base_frame: base_link

  update_frequency: 15.0 #局部代价地图的更新频率
  publish_frequency: 10.0 #局部代价地图发布的频率
  transform_tolerance: 0.5  #变换的缓冲容忍度

  # static_map: false  #启动后将使用静态地图
  rolling_window: true #局部代价地图是否使用滚动窗口
  width: 3.0 #局部代价地图的宽度
  height: 3.0 #局部代价地图的高度
  resolution: 0.02 #局部代价地图的分辨率  #0.04
  footprint: [[0.175, 0.14], [0.175, -0.14], [-0.175, -0.14], [-0.175, 0.14]] #机器人的底部轮廓，用于计算机器人与障碍物之间的距离
  inflation_radius: 0.15 #障碍物的膨胀半径
  cost_scaling_factor: 16.0 #代价地图的代价放大系数
  # footprint_padding: 0.05


  plugins:
    # - {name: static_map,       type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,        type: "costmap_2d::ObstacleLayer"}
    # - {name: costmap_prohibition_layer,        type: "costmap_prohibition_layer_namespace::CostmapProhibitionLayer"}     
    - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}

