TebLocalPlannerROS:
  acc_lim_x: 1.0
  acc_lim_y: 1.0
  acc_lim_theta: 2.5
  max_vel_x: 0.7
  max_vel_y: 0.7
  max_vel_theta: 3.0
  max_vel_x_backwards: 0.5
  min_turning_radius: 0
  footprint_model/type: "point" #line #polygon
  # footprint_model/line_start: [0.0,-0.25]
  # footprint_model/line_end: [0.0,0.25]
  # /footprint_model/vertices: [[0.175, 0.14], [0.175, -0.14], [-0.175, -0.14], [-0.175, 0.14]]
  is_footprint_dynamic: false
  ##------       Goal      ------
  xy_goal_tolerance: 0.10 #0.15
  yaw_goal_tolerance: 0.08
  free_goal_vel: false

  ## -----      Trajectory      -----
  dt_ref: 0.4
  dt_hysteresis: 0.08
  min_samples: 4
  global_plan_overwrite_orientation: false  #覆盖全局路径的方向是预留给3D路径规划使用的。对于车辆的2D规划，可以设置为False，可实现对全局路径的更好跟踪。
  global_plan_viapoint_sep: 0.1 #调整全局路径上选取的航迹点的间隔，应根据机器人的尺寸大小调整
  max_global_plan_lookahead_dist: 1.0 #部规划初始轨迹的最大长度
  force_reinit_new_goal_dist: 0.25
  force_reinit_new_goal_angular: 1.2
  feasibility_check_no_poses: 0 #在判断生成的轨迹是否冲突时使用，此时设置为3，即从轨迹起点开始逐个检查轨迹上的3个点，若3个点均不发生碰撞，则认为本次轨迹有效
  publish_feedback: false
  shrink_horizon_backup: true
  oscillation_recovery: false
  allow_init_with_backwards_motion: true #"allow_init_with_backwards_motion" 是 TEB（Timed Elastic Band）局部路径规划器的一个参数。TEB 是一种用于机器人路径规划的方法，特别适用于动态环境和非完美的定位情况。
#"allow_init_with_backwards_motion" 参数控制 TEB 规划器是否允许在初始化路径时考虑向后移动。如果设置为 true，那么在寻找到目标的最优路径时，规划器可以考虑向后移动。如果设置为 false，规划器则只会考虑向前移动。
#这个参数在某些情况下可能很有用，例如，如果机器人被困在一个狭窄的空间中，允许向后移动可能会找到一个更好的路径。然而，也要注意，允许向后移动可能会增加规划的复杂性和计算时间。
  exact_arc_length: True  #!!!!!!
  shrink_horizon_min_duration: 10.0

  ## -----     Obstacle Parameters      -----
  min_obstacle_dist: 0.155
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 0.3
  obstacle_poses_affected: 400
  inflation_dist: 0.40 # 0.145 # 障碍物膨胀距离。此膨胀只是降低通过这些区域的优先级，不应当用此距离迫使车辆远离障碍物。
  include_dynamic_obstacles: false
  legacy_obstacle_association: false
  obstacle_association_force_inclusion_factor: 2.0
  obstacle_association_cutoff_factor: 5.0
  # costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSMCCH"
  # # costmap_converter_plugin: ""
  # costmap_converter_spin_thread: true
  # costmap_converter_rate: 10.0

  ## -----    Optimization Parameters    -----
  no_inner_iterations: 5
  no_outer_iterations: 4
  penalty_epsilon: 0.10
  weight_max_vel_x: 1.0
  weight_max_vel_y: 1.0
  weight_max_vel_theta: 3.0
  weight_acc_lim_x: 1.0
  weight_acc_lim_y: 1.0
  weight_acc_lim_theta: 3.0
  weight_kinematics_nh: 10
  weight_kinematics_forward_drive: 1000.0
  weight_kinematics_turning_radius: 0
  weight_optimaltime: 0.4
  weight_obstacle: 100 
#weight_dynamic_obstacle: 10
  weight_viapoint: 1.0
  weight_inflation: 0.4
  weight_adapt_factor: 2.0
  
  ## -----     Parallel Planning in distinctive Topologies     -----
  enable_homotopy_class_planning: false
  enable_multithreading: true
  max_number_classes: 2
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 100.0
  selection_viapoint_cost_scale: 1.0
  selection_alternative_time_cost: false
  roadmap_graph_no_samples: 20
  roadmap_graph_area_width: 4
  h_signature_prescaler: 1.0
  h_signature_threshold: 0.1
  obstacle_heading_threshold: 1.0
  obstacle_keypoint_offset: 0.1
  visualize_hc_graph: false
  viapoints_all_candidates: true
  switching_blocking_period: 0.0
 
  odom_topic: "odom"
  map_frame: "map"


## -----     New Parameters Add     -----
  #teb_autosize: True
  #force_reinit_new_goal_angular: 0.78
  #control_look_ahead_poses: 1
  #prevent_look_ahead_poses_near_goal: 2
  #visualize_with_time_as_z_axis_scale: 0
  #
  #via_points_ordered: False
  #
  #use_proportional_saturation: False
  #transform_tolerance: 0.5
  #
  #wheelbase: 1.0
  #cmd_angle_instead_rotvel: False
  #
  max_vel_trans: 1.4
  #trans_stopped_vel: 0.1
  #theta_stopped_vel: 0.1
  #
  #dynamic_obstacle_inflation_dist: 0.6
  #
  #obstacle_proximity_ratio_max_vel: 1
  #obstacle_proximity_lower_bound: 0
  #obstacle_proximity_upper_bound: 0.5
  #
  #optimization_activate: True
  #optimization_verbose: False
  #
  #weight_shortest_path: 0
  #weight_dynamic_obstacle_inflation: 0.1
  #weight_velocity_obstacle_ratio
  #obstalce_cost_exponent: 10.135
  #
  #max_number_plans_in_current_class: 1
  #selection_prefer_initial_plan: 0.95
  #selection_alternative_time_cost: False
  #selection_dropping_probability: 0.0
  #roadmap_graph_area_length_scale: 1.0
  #
  # osclillation_recovery: True
  #
  #divergence_detection_enable: False
  #divergence_detection_max_chi_squared: 10
  #
  #simple_exploration: True
